CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(80) NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Stock" integer NOT NULL,
    "ImageUrl" text,
    "CategoryId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Carts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "ShippingAddress" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CartItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CartId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (1, 'Dispositivos y gadgets', 'Electronica');
INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (2, 'Moda y accesorios', 'Ropa');
INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (3, 'Articulos para el hogar', 'Hogar');
INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (4, 'Equipamiento deportivo', 'Deportes');
INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (5, 'Libros y material educativo', 'Libros');

INSERT INTO "Users" ("Id", "CreatedAt", "Email", "Name", "PasswordHash", "Role")
VALUES (1, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'admin@tienda.com', 'Admin', '$2a$11$h.5GT9T3KBkqMatH1w/GYeEoupvexDlMrsuWcXDQPTWvVPvXKO1YO', 'admin');
INSERT INTO "Users" ("Id", "CreatedAt", "Email", "Name", "PasswordHash", "Role")
VALUES (2, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'cliente@tienda.com', 'Cliente Demo', '$2a$11$lvGuq3WbCfWUqpSrv4it1OyV2y0gm7nMhskJIJFX828oN7lyE1vS6', 'customer');

INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (1, 1, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Laptop de alto rendimiento con procesador i9', 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400', 'Laptop Pro 15', 25999.99, 10);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (2, 1, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Telefono con camara de 108MP y pantalla AMOLED', 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400', 'Smartphone X12', 12499.99, 25);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (3, 1, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Cancelacion de ruido activa, 30h de bateria', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', 'Audifonos Wireless', 2999.99, 50);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (4, 2, TIMESTAMPTZ '2025-01-01T00:00:00Z', '100% algodon organico, corte slim', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400', 'Playera Premium', 349.99, 100);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (5, 4, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Amortiguacion avanzada para largas distancias', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', 'Tenis Running', 1899.99, 30);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (6, 3, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Soporte lumbar ajustable, ideal para home office', 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400', 'Silla Ergonomica', 4599.99, 15);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (7, 5, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Robert C. Martin, guia de buenas practicas', 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400', 'Clean Code', 499.99, 40);
INSERT INTO "Products" ("Id", "CategoryId", "CreatedAt", "Description", "ImageUrl", "Name", "Price", "Stock")
VALUES (8, 1, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Monitor cardiaco, GPS, resistente al agua', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', 'Smartwatch Serie 5', 3799.99, 20);

CREATE INDEX "IX_CartItems_CartId" ON "CartItems" ("CartId");

CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");

CREATE UNIQUE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");

CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Products"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Products") + 1,
        nextval(pg_get_serial_sequence('"Products"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260615194734_InitialCreate', '8.0.0');

COMMIT;

